const HomePage = () => (
  <div>
    <h1>Welcome to our page!</h1>
    <p>
      Are you ready to put your math skills to the test? With our calculator web app, you can solve
      equations, perform calculations, and crunch numbers until your heart&apos;s content. Whether
      you&apos;re
      a student, a professional, or just someone who loves math, our calculator is the perfect tool
      for you.
    </p>
    <p>
      So, what are you waiting for? Try our calculator web app today and see how far you can push
      it! With its robust features and intuitive design, you&apos;ll be able to tackle even the most
      complex math problems with ease. So go ahead, give it a try, and see how far you can go! Who
      knows, you might even break it!
    </p>
    <p>
      <q>
        Text generated by ChatGPT
      </q>
    </p>
  </div>
);

export default HomePage;
